namespace Simple_QR_Code_Maker.Models;

public readonly record struct EmojiLogoPreset(string Emoji, string Name);

public static class EmojiLogoPresets
{
    public static IReadOnlyList<EmojiLogoPreset> All { get; } =
    [
        new("😀", "Smile"),
        new("😁", "Grin"),
        new("😂", "Laugh"),
        new("🤣", "ROFL"),
        new("😊", "Happy"),
        new("😎", "Cool"),
        new("😮", "Wow"),
        new("😍", "Love"),
        new("🥰", "Adore"),
        new("🥳", "Celebrate"),
        new("🤖", "Robot"),
        new("👍", "Like"),
        new("👏", "Applause"),
        new("🙏", "Thanks"),
        new("👑", "Crown"),
        new("🚀", "Rocket"),
        new("⭐", "Star"),
        new("⚡", "Lightning"),
        new("✨", "Shine"),
        new("❗", "Alert"),
        new("❓", "Question"),
        new("🔥", "Fire"),
        new("💡", "Idea"),
        new("💎", "Gem"),
        new("✅", "Check"),
        new("❤️", "Heart"),
        new("💜", "Purple Heart"),
        new("🎯", "Target"),
        new("🎉", "Party"),
        new("🏆", "Trophy"),
        new("🥇", "Gold Medal"),
        new("📦", "Package"),
        new("📢", "Announcement"),
        new("📈", "Growth"),
        new("🛒", "Cart"),
        new("💼", "Briefcase"),
        new("💰", "Money"),
        new("☕", "Coffee"),
        new("⌛", "Time"),
        new("🕒", "Clock"),
        new("🍩", "Donut"),
        new("🎁", "Gift"),
        new("🎵", "Music"),
        new("🎮", "Gaming"),
        new("📷", "Camera"),
        new("🎬", "Movie"),
        new("🧠", "Brain"),
        new("👤", "Person"),
        new("👥", "Contacts"),
        new("📇", "Contact Card"),
        new("📍", "Pin"),
        new("📱", "Phone"),
        new("☎️", "Telephone"),
        new("✉️", "Email"),
        new("📧", "Envelope"),
        new("🏠", "Home"),
        new("🏡", "House"),
        new("🏢", "Office"),
        new("💻", "Laptop"),
        new("🌎", "Globe"),
        new("🌈", "Rainbow"),
        new("🌻", "Sunflower"),
        new("🐱", "Cat"),
        new("🐶", "Dog"),
        new("🦊", "Fox"),
        new("🐼", "Panda"),
        new("🍕", "Pizza"),
        new("🍔", "Burger"),
        new("🍟", "Fries"),
        new("🍓", "Strawberry"),
        new("🌟", "Sparkles"),
        new("🔒", "Lock"),
        new("🔔", "Bell"),
        new("🛡️", "Shield"),
    ];
}
