
namespace Simple_QR_Code_Maker.Models;

public class FaqItem
{
    public string Title { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;

    public static readonly FaqItem[] AllFaqs = [
        new FaqItem { Title = "What is a QR Code?", Content = "It is best to think of QR Codes as text in a format computers can easily read. More specifically they are a format of two-dimensional barcode that is used to encode content. QR Codes may be used to display text to the user, to open a URL, and many other things. But most frequently are just used for opening websites."},
        new FaqItem { Title = "Why can QR Codes be dangerous?", Content = "Due to the fact that most people use QR Codes to quickly open websites this introduces a risk because it is not clear what website is encoded into the QR Code. Additionally when the URL to the website is redirected then the owner of the URL would be able to change where the QR Code sends people scanning the code whenever they want."},
        new FaqItem { Title = "Are these dynamic QR Codes?", Content = "QR Codes are not dynamic on their own. To make a QR Code dynamic you need to use a link which will redirect/forward to another link." },
        new FaqItem { Title = "How can you tell if a QR Code is dynamic?", Content = "Compare the final website with the QR Code content. If when you scan the QR Code with your phone and it goes to a website say, https://www.example.com but when you use this app to read the code and it is a totally different URL like http://JoeFinApps.com/123, then the QR Code is likely dynamic or at the very least being redirected by the domain in the QR Code." },
        new FaqItem { Title = "What is a two-dimensional barcode", Content="Barcodes are content which has been translated into a format which can be easily scanned by a machine. The barcodes you see on most products which are a row of lines with different widths are a form of one-dimensional barcodes because they are only one row of data. Two-dimensional barcodes encode data into a pattern which is multiple rows. The data is not always encoded left-to-right or top-to-bottom. Frequently two-dimensional barcodes wrap or pack the data in unique ways depending on the type of code."},
        new FaqItem { Title = "How to read a QR Code?", Content = "To read a QR Code, you need a scanner which can read 2-dimensional (2D) barcodes. Android, iOS, and Windows all support QR Code scanning in the native default camera apps. To scan the code, simply open the app and hold the camera in front of it. The app will automatically recognize the code and act accordingly. NOTE: this does not mean the webpage you are sent to is exactly what is encoded into the QR Code. To read the content of a QR Code use the Read Code page of this app and open an image or paste one from your clipboard." },
        new FaqItem { Title = "What is the Error Correction Level?", Content = "All QR Codes can still be readable even if some of the QR Code is hidden due to damage or challenging conditions. The amount of the QR Code which can be hidden and the code still work is called the Error Correction Level. A higher error correction level will be more durable however the minimum size will be larger due to more data being encoded in the QR Code." },
        new FaqItem { Title = "How to put an image inside of the center of a QR Code?", Content = "Take the QR Code from this app and place it in any image editing software and overlay the image you want over the center. Test to make sure the image you place is not too large. QR Codes are can accept some error (how much depends on the error correction level used when making the QR Code) which means you can put an image in the middle of a QR Code and cover up some of the QR Code. Always test QR Codes in application when hiding any part of the QR Code to make sure it still scans easily." },
        new FaqItem { Title = "How is minimum size calculated?", Content = "The minimum size of a QR Code is calculated based experimental data. QR Codes at several sizes were printed using a 600dpi laser printer on white paper. The codes were scanned and a relationship between code size and scan distance was developed. The contrast between the QR Code's foreground and background is also factored into the minimum size." },
        new FaqItem { Title = "How can I change the maximum scan distance?", Content = "You can the maximum estimated scan distance of the minimum QR Code size in the settings. As always test in the real world before committing to a costly order or placement."},
        new FaqItem { Title = "What is the contrast ratio?", Content = "The contrast ratio is the difference in luminance or color that makes an object distinguishable. In the context of QR Codes, the contrast ratio is the difference in color between the foreground and background of the code. A higher contrast ratio makes the code easier to scan and read. The minimum recommended contrast ratio for QR Codes is 2.5:1." },
        new FaqItem { Title = "At the minimum size, how far away can a QR Code be scanned?", Content = "36 inches or 1 meter is roughly the maximum scan distance of a QR Code printed at the minimum size. Physical factors like lighting conditions, damaged codes, and glare will all change how easy (if at all) a QR Code can be scanned." },
        new FaqItem { Title = "What if I print the QR Code smaller than the minimum size?", Content = "The scan distance and size have a linear relationship so doubling the QR Code size doubles the scan distance; the same goes for increasing the size." },
        new FaqItem { Title = "What type of scanner or phone camera is expected when printing at the minimum size?", Content = "The scanning experiments were carried out using an iPhone 13 and the default iOS code-scanning app and the main camera. The camera is a 12 Megapixel (MP) camera. Any modern Android or iOS phone after 2018 should be able to scan QR Codes at 1 meter at the default minimum size." },
        new FaqItem { Title = "Will the scanning always work if minimum size is followed?", Content = "No. The minimum size assumes good conditions such as: a well lit environment, matte printed surface, a decently modern scanning device." },
        new FaqItem { Title = "Why do we have to use QR Codes?", Content = "Typing in URLs is tedious so having the camera scan it easier and more reliable." },
        new FaqItem { Title = "Are QR Codes evil and/or dumb?", Content = "A little of both, but they can be a handy way to get people to websites." },
        ];
}
