name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: msbuild "Simple QR Code Maker.sln" /t:Restore /p:Configuration=Release

    - name: Build solution
      run: msbuild "Simple QR Code Maker.sln" /p:Configuration=Release /p:Platform=x64
